

import type { Student, Project, Survey, Mentor, Company, Milestone, Course, UserRole } from './types';

const studentMilestones: Milestone[] = [
    { id: 'nda', text: 'Submit Signed NDAs', status: 'completed', dueDate: '2024-01-20' },
    { id: 'action-plan', text: 'Submit Project Action Plan', status: 'completed', dueDate: '2024-02-01' },
    { id: 'mid-review', text: 'Complete Mid-Point Review', status: 'pending', dueDate: '2024-03-15' },
    { id: 'testimonial', text: 'Submit Written Testimonial', status: 'pending', dueDate: '2024-05-01' },
    { id: 'company-feedback-review', text: 'Review Company Feedback', status: 'pending', dueDate: '2024-05-05' },
    { id: 'video', text: "Upload 'Lesson Learned' Video (Student)", status: 'pending', dueDate: '2024-05-01' },
    { id: 'final-report', text: 'Submit Final Report', status: 'pending', dueDate: '2024-05-12' },
    { id: 'case-study', text: 'Submit Case Study', status: 'pending', dueDate: '2024-05-14' },
    { id: 'survey', text: 'Complete Post-Capstone Survey', status: 'pending', dueDate: '2024-05-10' },
    { id: 'final-video', text: 'Submit Final Combined Video (Student & Company)', status: 'pending', dueDate: '2024-05-15' },
];

export const students: Student[] = [
  {
    id: '1',
    role: 'Student',
    firstName: 'Aisha',
    lastName: 'Khan',
    fullName: 'Aisha Khan',
    email: 'aisha.khan@example.com',
    createdAt: '2024-01-02',
    updatedAt: '2024-05-11',
    studentProfile: {
      studentIdNumber: 'S001',
      skills: ['JavaScript', 'React', 'Node.js', 'Data Analysis'],
      resumeText: 'Aisha Khan has a strong background in web development and data analysis. She has worked on several projects involving front-end development with React and back-end with Node.js. She is also proficient in using data analysis tools to derive insights.',
      status: 'Approved',
      projectId: 'p1',
      mentorId: 'm1',
      ndaStatus: 'Signed',
      gpa: 3.9,
      registrationDate: '2024-01-10',
      milestones: studentMilestones.map(m => ['nda', 'action-plan'].includes(m.id) ? {...m, status: 'completed'} : m),
      program: 'DBA',
    }
  },
  {
    id: '2',
    role: 'Student',
    firstName: 'Ben',
    lastName: 'Carter',
    fullName: 'Ben Carter',
    email: 'ben.carter@example.com',
    createdAt: '2024-01-05',
    updatedAt: '2024-05-05',
    studentProfile: {
      studentIdNumber: 'S002',
      skills: ['Python', 'Machine Learning', 'TensorFlow', 'Project Management'],
      resumeText: 'Ben Carter is a machine learning enthusiast with experience in developing predictive models using Python and TensorFlow. He has a proven track record of managing projects from conception to completion and is an excellent communicator.',
      status: 'Approved',
      projectId: 'p1',
      mentorId: 'm1',
      ndaStatus: 'Pending',
      gpa: 3.8,
      registrationDate: '2024-01-12',
      milestones: studentMilestones.map(m => m.id === 'nda' ? {...m, status: 'pending', dueDate: '2024-01-20'} : m),
      program: 'MSIT',
    }
  },
  {
    id: '3',
    role: 'Student',
    firstName: 'Carla',
    lastName: 'Rodriguez',
    fullName: 'Carla Rodriguez',
    email: 'carla.rodriguez@example.com',
    createdAt: '2024-02-01',
    updatedAt: '2024-05-01',
    studentProfile: {
      studentIdNumber: 'S003',
      skills: ['UX/UI Design', 'Figma', 'Adobe XD', 'User Research'],
      resumeText: 'Carla Rodriguez is a creative UX/UI designer with a passion for creating intuitive and user-friendly interfaces. She is skilled in using Figma and Adobe XD for prototyping and has conducted extensive user research to inform her design decisions.',
      status: 'Approved',
      projectId: 'p2',
      mentorId: 'm1',
      ndaStatus: 'Signed',
      gpa: 3.7,
      registrationDate: '2024-02-05',
      milestones: studentMilestones.map(m => ({...m, status: 'pending'})),
      program: 'BSc',
    }
  },
  {
    id: '4',
    role: 'Student',
    firstName: 'David',
    lastName: 'Lee',
    fullName: 'David Lee',
    email: 'david.lee@example.com',
    createdAt: '2024-02-10',
    updatedAt: '2024-05-10',
    studentProfile: {
      studentIdNumber: 'S004',
      skills: ['Java', 'Spring Boot', 'Microservices', 'AWS'],
      resumeText: 'David Lee is a software engineer specializing in building scalable microservices with Java and Spring Boot. He has experience deploying applications on AWS and is knowledgeable about cloud architecture best practices.',
      status: 'Approved',
      ndaStatus: 'Pending',
      gpa: 3.9,
      registrationDate: '2024-02-15',
      milestones: [],
      program: 'DBA',
    }
  },
   {
    id: '5',
    role: 'Student',
    firstName: 'Emily',
    lastName: 'White',
    fullName: 'Emily White',
    email: 'emily.white@example.com',
    createdAt: '2024-02-28',
    updatedAt: '2024-05-08',
    studentProfile: {
      studentIdNumber: 'S005',
      skills: ['Data Science', 'R', 'SQL', 'Tableau'],
      resumeText: 'Emily White is a data scientist with a knack for storytelling with data. Proficient in R and SQL, she creates compelling visualizations in Tableau to communicate complex findings to stakeholders.',
      status: 'Pending',
      projectId: 'p4',
      ndaStatus: 'Signed',
      gpa: 3.6,
      registrationDate: '2024-03-01',
      milestones: studentMilestones,
      program: 'BSc',
    }
  },
  {
    id: '6',
    role: 'Student',
    firstName: 'Frank',
    lastName: 'Miller',
    fullName: 'Frank Miller',
    email: 'frank.miller@example.com',
    createdAt: '2024-03-15',
    updatedAt: '2024-05-15',
    studentProfile: {
      studentIdNumber: 'S006',
      skills: ['Cybersecurity', 'Penetration Testing', 'Network Security', 'Python'],
      resumeText: 'Frank Miller is a cybersecurity analyst with hands-on experience in penetration testing and network security. He uses Python to automate security tasks and is passionate about protecting digital assets.',
      status: 'Pending',
      ndaStatus: 'Pending',
      gpa: 3.5,
      registrationDate: '2024-03-20',
      milestones: [],
      program: 'MSIT',
    }
  },
];

export const projects: Project[] = [
  {
    id: 'p1',
    name: 'AI-Powered Data Visualization Platform',
    company: 'Innovate Inc.',
    description: 'Develop an interactive platform that uses AI to automatically generate insightful visualizations from raw data sets. Requires skills in data analysis, machine learning, and front-end development (React).',
    status: 'Ongoing',
    studentIds: ['1', '2'],
    mentorIds: ['m1'],
    courseIds: ['c1'],
    startDate: '2024-01-15',
    completionDate: '2024-05-15',
  },
  {
    id: 'p2',
    name: 'Mobile-First E-commerce App',
    company: 'ShopSphere',
    description: 'Create a new mobile e-commerce application with a heavy focus on user experience and intuitive design. Looking for a student with strong UX/UI design skills and experience in user research.',
    status: 'Ongoing',
    studentIds: ['3'],
    mentorIds: ['m1'],
    courseIds: ['c2'],
    startDate: '2024-02-01',
    completionDate: '2024-06-01',
  },
  {
    id: 'p3',
    name: 'Cloud-Native Backend System',
    company: 'DataCore',
    description: 'Build a robust and scalable backend system for a high-traffic application using microservices architecture. Ideal candidates have experience with Java, Spring Boot, and cloud platforms like AWS.',
    status: 'Completed',
    studentIds: [],
    mentorIds: [],
    courseIds: [],
    startDate: '2023-09-01',
    completionDate: '2024-01-01',
  },
  {
    id: 'p4',
    name: 'Data Pipeline Automation',
    company: 'Innovate Inc.',
    description: 'Design and implement a fully automated data pipeline for real-time analytics. This project involves working with large datasets, ETL processes, and scheduling tools like Airflow. Strong Python and SQL skills are essential.',
    status: 'Ongoing',
    studentIds: ['5'],
    mentorIds: [],
    courseIds: ['c1'],
    startDate: '2024-08-01',
    completionDate: '2024-12-01',
  },
   {
    id: 'p5',
    name: 'Cybersecurity Threat Detection Model',
    company: 'SecureNet',
    description: 'Develop a machine learning model to detect and classify cybersecurity threats in real-time network traffic. Requires a deep understanding of network protocols, machine learning algorithms, and cybersecurity principles.',
    status: 'Not Assigned',
    studentIds: [],
    mentorIds: [],
    courseIds: [],
    startDate: '2024-09-01',
    completionDate: '2025-01-01',
  }
];

export const surveys: Survey[] = [
  {
    id: 's1',
    title: 'Post-Internship Feedback 2024',
    type: 'Student Satisfaction',
    status: 'Active',
    responses: 84,
    totalParticipants: 150,
    createdAt: '2024-05-10',
    dueDate: '2024-07-10',
    lastReminderSent: '2024-06-20',
  },
  {
    id: 's2',
    title: 'Student Skills Self-Assessment',
    type: 'Self-Assessment',
    status: 'Active',
    responses: 112,
    totalParticipants: 150,
    createdAt: '2024-05-15',
    dueDate: '2024-07-15',
  },
  {
    id: 's3',
    title: 'Project Interest Survey',
    type: 'Student Satisfaction',
    status: 'Closed',
    responses: 95,
    totalParticipants: 100,
    createdAt: '2024-04-20',
    dueDate: '2024-05-20',
  },
  {
    id: 's4',
    title: 'Safirnaction Objectives Alignment',
    type: 'Company Feedback',
    status: 'Closed',
    responses: 76,
    totalParticipants: 80,
    createdAt: '2024-04-01',
    dueDate: '2024-05-01',
  },
    {
    id: 's5',
    title: 'Innovate Inc. Satisfaction Survey',
    type: 'Company Feedback',
    status: 'Active',
    responses: 15,
    totalParticipants: 25,
    createdAt: '2024-06-01',
    dueDate: '2024-07-01',
    lastReminderSent: '2024-06-15',
  },
];

export const mentors: Mentor[] = [
  {
    id: 'm1',
    role: 'Mentor',
    firstName: 'Dr. Evelyn',
    lastName: 'Reed',
    fullName: 'Dr. Evelyn Reed',
    email: 'e.reed@university.edu',
    createdAt: '2023-12-01',
    updatedAt: '2024-05-01',
    mentorProfile: {
      skills: ['AI/ML', 'Data Science', 'Python', 'Natural Language Processing'],
      pastProjects: [
        'Sentiment Analysis for Customer Feedback',
        'Predictive Maintenance for Industrial IoT',
        'Image Recognition for Retail',
      ],
      menteeIds: ['1', '2', '3'],
      status: 'Active',
    }
  },
  {
    id: 'm2',
    role: 'Mentor',
    firstName: 'Prof. Samuel',
    lastName: 'Chen',
    fullName: 'Prof. Samuel Chen',
    email: 's.chen@university.edu',
    createdAt: '2023-12-05',
    updatedAt: '2024-05-05',
    mentorProfile: {
      skills: ['Web Development', 'React', 'Node.js', 'Cybersecurity'],
      pastProjects: [
        'E-commerce Platform Overhaul',
        'Secure API Gateway Implementation',
      ],
      menteeIds: [],
      status: 'Available',
    }
  }
];


export const companies: Company[] = [
    {
        id: 'c1',
        name: 'Innovate Inc.',
        projects: [projects[0], projects[3]],
        surveyCompleted: true,
    },
    {
        id: 'c2',
        name: 'ShopSphere',
        projects: [projects[1]],
        surveyCompleted: false,
    },
    {
        id: 'c3',
        name: 'DataCore',
        projects: [projects[2]],
        surveyCompleted: false,
    }
];

export const courses: Course[] = [
    {
      id: 'c1',
      title: 'Advanced AI Capstone',
      code: 'CS599',
      schedule: 'TTh 2:00 - 3:30',
      delivery: 'online',
      studentIds: ['1', '2', '5'],
      mentorId: 'm1',
    },
    {
      id: 'c2',
      title: 'UX/UI Design Workshop',
      code: 'DES450',
      schedule: 'MWF 10:00 - 11:30',
      delivery: 'in-person',
      classroom: 'Building C, Room 201',
      studentIds: ['3'],
      mentorId: 'm1',
    }
]
